export { default as Logo } from './Logo'
export { default as Eyes } from './Eyes'
export { default as Facebook } from './Facebook'
export { default as Instagram } from './Instagram'
export { default as Close } from './X'
export { default as VerticalEyes } from './VerticalEyes'
export { default as VerticalThykjo } from './VerticalThykjo'
export { default as VerticalVerkefni } from './VerticalVerkefni'
